# Snakemake configuration
#

main_target: [slides]
# dependencies
slides: []

# Specifies  that  headers  with the specified level create slides (for beamer,
# s5, slidy, slideous, dzsâ€ lides).  Headers above this level in the hierarchy
# are used to divide the  slide  show  into  sections; headers  below  this
# level create subheads within a slide.  The default is to set the slide level
# based on the contents of the document; see Structuring the slide show.
#
slidelevel: 2
